name: Node.js CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci

  run-linters:
    name: Run Linters
    needs: install
    steps:
      - name: Run eslint
        run: npm run lint
      - name: Run prettier
        run: npm run format:check
