name: Node.js CI

on: [push]

jobs:
  install:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
      - run: npm install
  
  validation:
    needs: [install]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
      - run: npm run lint
      - run: npm run prettier
